metadata:
    name: Configuration loader
    format: "Lava-Test Test Definition 1.0"
    description: "Configuration for Connect-Devices with specific modules is loaded"
    maintainer:
        - r.gsponer@kunbus.com
    os:
        - raspian
    scope:
        - functional
    devices:
        - Connect
        - Connect+
        - Connect S
        - Connect SE
run:
    steps:
        - cd automated/device-config/connect
        - bash ./config_loader.sh
